/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Connection_OnMessageReceivedListener */

#ifndef _Included_Connection_OnMessageReceivedListener
#define _Included_Connection_OnMessageReceivedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
